### ISSUE TITLE
Where abouts is the context stuff combined?

### ISSUE THREAD

**Issue by Henry-E** [kelvinguu/neural-editor#3]
My oversimplified interpretation of how the model seems to work is; The encoder hidden states have some random normal noise added to them. Then these hidden states are combined with the input word vector for the decoder. And then it's trained like a regular language model.

The only thing I wasn't able to find was the part of the code that does the context combining? All the context combiner classes and their parent classes appear to be empty.

**Comment by NickShahML** [comment]
@Henry-E It seems to me that this random_noise from the edit vector is only applicable in the Yelp dataset. It looks for the Google corpus that they set this random_noise edit vector to zero. So honestly, I think it really is just a plain seq2seq model in this case.

For context combining, are you referring to the scripts that organize the dataset and pair sentences up based upon the Jaccard Distance as they describe in the LSH part of the paper?

**Comment by Henry-E** [comment]
My guess would be that if it's turned off for the google corpus that might just be an experimentation thing to get a baseline. 

With regards to the context combining, it happens here https://github.com/kelvinguu/neural-editor/blob/0e6dd327a79ff060e383d0bf654e8cc7d942c380/third-party/gtd/gtd/ml/torch/decoder.py#L120
Where it combines the encoder hidden states, with additional noise added to them, and the input word embeddings to the decoder. However if you follow the chain of inheritance for the context combiner function, it doesn't appear that there's any working code for it? In the papers it's supposed to be simply concatenation but it seems unlikely that it would concatenate all hidden states from a variable length sequence. Anyway, based on the paper I didn't realise that the edit vector would be directly combined with the encoded hidden states. It sounded like a separate, randomly generated numerical vector that was concatenated with the decoder input word vectors.

**Comment by Henry-E** [comment]
But you know, I probably just haven't gone through all the folders in enough detail to find it yet. I think I was looking at the language model code when I should have been focused on the edit model instead.

**Comment by NickShahML** [comment]
@Henry-E, if you look at the `agenda.py` in edit_model you'll find that they just concat the input to the decoder plus the the edit_vector. They then apply a linear layer after this before it enters the first layer of the LSTM.
