### ISSUE TITLE
Reproducible experiments on FloydHub

### ISSUE THREAD

**Issue by ReDeiPirati** [kelvinguu/neural-editor#4]
Hi @kelvinguu,

First of all, really interesting paper!! What do you think about creating a public project on FloydHub for having reproducible experiments and simplify the way in which other research or AI passionate can interact/play with it?

**Comment by Henry-E** [comment]
Percy Liang's students are usually pretty good about uploading stuff to [codalab](https://worksheets.codalab.org/worksheets/0x9b6bb6fdd4aa4bf1b120300fd95f944a/)

**Comment by kelvinguu** [comment]
In the near future, we will indeed be sharing more reproducible results on codalab.org, as Henry-E mentioned. But thanks for pointing out FloydHub -- looks cool!
