### ISSUE TITLE
Improving Edit Pairs with Different Distance Metrics

### ISSUE THREAD

**Issue by NickShahML** [kelvinguu/neural-editor#5]
Hey @kelvinguu and @thashim thanks for your help so far. I've been doing some more research on deciding how to measure the "closest" sentence to create your training dataset (edit pairs).

First off, I think BFS is absolutely necessary especially for the bigger datasets. But the methodology of measurement between sentences I feel can be improved:

1. Doc2Vec Cosine Distance. In this approach you use doc2vec and train the model on each sentence which yields a final vector for each sentence. You then find the closest sentences to your prototype based upon cosine distance. I've tried this method already and unfortunately, it doesn't seem to find similarly worded sentences.

2. Edit Distance. In this approach, you use edit distance instead of Jaccard which offers the benefit of gpu usage (see tensorflow's [edit_distance](https://www.tensorflow.org/api_docs/python/tf/edit_distance)). In this method, deletions have a higher weight.

3. Word2Vec Averaging + Cosine Distance. In this approach you take the word vectors of each sentence, then average them to get a final vector for the sentence. You then compare cosine distances. I feel that this approach would be the best because it accounts for similarity between words. For instance, "feeling" and "feelings" are treat similarly. In Jaccard and Edit Distance, this does not occur.

4. Jaccard Distance Without Stop Words. In this approach, you take out all stop words in a sentence and then measure the jaccard distance. This would hopefully give you a better match semantically. This could be added in addition to taking the original Jaccard distance.

Obviously, you guys worked really hard, and these were all approaches you probably thought of already. If you could comment on why you chose vanilla Jaccard over these, it would be much appreciated!

**Comment by kelvinguu** [comment]
Hi Nick, thanks for your comments and observations! We chose Jaccard distance due to its conceptual simplicity, good correlation with semantics (as reported in the paper), and efficiency for finding nearest neighbors.

But I absolutely agree that better distance metrics and other methods to retrieve prototypes should be investigated. We just wanted to start with the simplest implementation of this idea.
